apiVersion: v1
kind: ConfigMap
metadata:
  name: kube-login
data:
  CALLBACK_URL: https://kube-login.domain.com/callback
  CLIENT_ID: login-app
  OIDC_ISSUER: https://dex-deployment.domain.com/dex
  REFRESH_CLIENT_ID: kubectl
---
apiVersion: v1
kind: Secret
metadata:
  name: kube-login
type: Opaque
data:
  CLIENT_SECRET: <dex static client secret base64>
---
apiVersion: v1
kind: Secret
metadata:
  name: kube-login.domain.com.tls
type: kubernetes.io/tls
data:
  tls.crt: <base64 cert>
  tls.key: <base64 key>
