apiVersion: v1
kind: ConfigMap
metadata:
  name: ${CI_PROJECT_NAME}
  namespace: ${NAMESPACE}
data:
  CALLBACK_URL: https://${CI_PROJECT_NAME}.domain.com/callback
  CLIENT_ID: agi-login
  OIDC_ISSUER: https://kube-dex.domain.com/dex
  REFRESH_CLIENT_ID: kubectl
---
apiVersion: v1
kind: Secret
metadata:
  name: ${CI_PROJECT_NAME}
  namespace: ${NAMESPACE}
type: Opaque
data:
  CLIENT_SECRET: <dex static client secret base64>
---
apiVersion: v1
kind: Secret
metadata:
  name: ${CI_PROJECT_NAME}.domain.com.tls
  namespace: ${NAMESPACE}
type: kubernetes.io/tls
data:
  tls.crt: <base64 cert>
  tls.key: <base64 key>
