apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: kube-login
  labels:
    app: kube-login
spec:
  revisionHistoryLimit: 2
  replicas: 1
  selector:
    matchLabels:
      app: kube-login
  template:
    metadata:
      labels:
        app: kube-login
    spec:
      containers:
      - image: roffe/kube-login:latest
        resources:
          requests:
            memory: 5Mi
            cpu: 5m
          limits:
            memory: 15Mi
            cpu: 70m
        name: kube-login
        ports:
        - name: http
          containerPort: 5556
        env:
        - name: KUBE_APISERVER
          value: "https://address.to.kubernetes.api"
        - name: CLIENT_ID
          valueFrom:
            configMapKeyRef:
              name: kube-login
              key: CLIENT_ID
        - name: CLIENT_SECRET
          valueFrom:
            secretKeyRef:
              name: kube-login
              key: CLIENT_SECRET
        - name: OIDC_ISSUER
          valueFrom:
            configMapKeyRef:
              name: kube-login
              key: OIDC_ISSUER
        - name: CALLBACK_URL
          valueFrom:
            configMapKeyRef:
              name: kube-login
              key: CALLBACK_URL
        command: ["/login"]
        args:
          - --client-id=$(CLIENT_ID)
          - --client-secret=$(CLIENT_SECRET)
          - --issuer-root-ca=/var/run/secrets/kubernetes.io/serviceaccount/ca.crt
          - --issuer=$(OIDC_ISSUER)
          - --listen=http://0.0.0.0:5556
          - --redirect-uri=$(CALLBACK_URL)
          - --api-server=$(KUBE_APISERVER)
