apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: kube-login-ingress
  annotations:
    ingress.kubernetes.io/ssl-redirect: 'true'
spec:
  tls:
  - hosts:
    - kube-login.domain.com
    secretName: kube-login.domain.com.tls
  rules:
  - host: kube-login.domain.com
    http:
      paths:
      - path: /
        backend:
          serviceName: kube-login
          servicePort: 5556

